version: '3'
services:
  mysql:
    image: yoojia/mysql:alpine-armv7
    container_name: rpi-mysql-server
    hostname: rpi-mysql-server
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=5XSwBxGx
#      - MYSQL_DATABASE=temps
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=pi
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    privileged: true
    read_only: false
