version: '2'

services:
  mysql:
    image: yoojia/mysql:alpine-armv7
    container_name: rpi-mysql-server
    hostname: rpi-mysql-server
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=5XSwBxGx
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=pi
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    privileged: true
    read_only: false
    networks:
      extnetwork:
        ipv4_address: 173.10.0.2
  httpd:
    image: theteapot418/apache-php7.1-arm
    container_name: rpi-apache-php7
    hostname: rpi-apache-php-server
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    ports:
      - "8080:80"
    volumes:
      - ./www:/www
    restart: unless-stopped
    networks:
      extnetwork:
        ipv4_address: 173.10.0.3

networks:
  extnetwork:
    ipam:
       config:
         - subnet: 173.10.0.0/16
           gateway: 173.10.0.1
